# Ironman SP branch only. Do not check in other branch.

include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  r63319_wqhd_tianma_ironmantb_2k_vdo.o

# Ironman SP branch only. Do not check in other branch.